# -*- coding: utf-8 -*-
"""chatbot_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ypneevvIhThZ4Sm249N6PnNRy72Hqu8v
"""

import nltk
nltk.download('punkt_tab')

import pandas as pd
from nltk.tokenize import word_tokenize
from datetime import datetime

df_karyawan = pd.read_csv('dataset_chatbot_updated.csv')
df_pertanyaan = pd.read_csv('dataset_pertanyaan_chatbot.csv', delimiter=';')

df_karyawan.head()

df_pertanyaan.head()

def chatbot_response(id_karyawan, question):
  #cek karyawan
  employee = df_karyawan[df_karyawan['ID_Karyawan'] == id_karyawan]
  if employee.empty:
    return "ID tidak ditemukan"
  jabatan = employee['Jabatan'].iloc[0]
  department = employee['Department'].iloc[0]
  sisa_cuti = employee['Jatah_Cuti'].iloc[0] - employee['Cuti_Terpakai'].iloc[0]
  riwayat = employee['Riwayat_Pengajuan_Cuti'].iloc[0]

  #Tokenisasi pertanyaan
  tokens = word_tokenize(question.lower())

  #Maatch dengan tabel 2
  for _, row in df_pertanyaan.iterrows():
    if row['Pertanyaan'].lower() in question.lower():
      jawaban = row['Jawaban']
      #Personalisasi jawaban
      if 'cuti' in tokens and ('sisa' in tokens or 'berapa' in tokens):
        return f"Halo id {id_karyawan}, {jawaban.replace('[Sisa_Cuti]', str(sisa_cuti))}"
      elif 'cuti' in tokens or 'riwayat' in tokens:
        return f"halo id {id_karyawan}, {jawaban.replace('[Riwayat_Pengajuan_Cuti]', riwayat)}"
      elif 'gajian' in tokens:
        return f"halo id {id_karyawan}, {jawaban}"
      return f"Halo id {id_karyawan}, {jawaban}"
  return f"Halo id {id_karyawan}, Maaf saya tidak mengerti pertanyaan anda"

#Test
while True:
  id_karyawan = int(input('Masukkan ID Karyawan (3 digit): '))
  question = input('Masukkan pertanyaan:')
  print(chatbot_response(id_karyawan, question))
  if input('Lanjut? (y/n): ') == 'n':
    break